name: Draft release
on: workflow_dispatch
jobs:
  build:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add x86_64-unknown-linux-gnu
      - run: rustup target add x86_64-apple-darwin
      - run: rustup target add x86_64-pc-windows-msvc
      - run: cargo build --bin main --release --target x86_64-unknown-linux-gnu
      - run: cargo build --bin main --release --target x86_64-apple-darwin
      - run: cargo build --bin main --release --target x86_64-pc-windows-msvc
      - run: |
          git config user.name "GitHub Actions"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - run: git checkout -b temp-$RANDOM
      - run: git add -Af
      - run: git commit --allow-empty -m 'Draft release'
      - run: git push -u origin "$(git branch --show-current)"
      - run: gh release create '?' --draft --target $(git rev-parse HEAD~1)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - if: always()
        run: git push -d origin "$(git branch --show-current)"
