name: Draft Release
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: macos-latest, target: x86_64-apple-darwin }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      target: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add "$target"
      - run: cargo fetch
      - run: cargo build --bin main --locked --release --target "$target"
      # - run: cargo build --bin pre --locked --release --target "$target"
      # - run: cargo build --bin post --locked --release --target "$target"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            target/release/main
            # target/release/pre
            # target/release/post
  draft-release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: tree -a
      - run: |
          for target in *; do
            pushd "$target"
            if [[ $target == *windows* ]]; then
              zip -r "../$target.zip" .
            else
              tar -zcvf "../$target.tar.gz" .
            fi
            popd
            rm -rf "$target"
          done
      - run: gh release create ' ' ./* --draft 
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          
