name: Draft Release
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: macos-latest, target: x86_64-apple-darwin }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      MY_TARGET: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add "$MY_TARGET"
      - run: cargo build --bin main --release --target "$MY_TARGET"
      # - run: cargo build --bin pre --release --target "$MY_TARGET"
      # - run: cargo build --bin post --release --target "$MY_TARGET"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/main
            target/${{ matrix.target }}/release/main.exe
            target/${{ matrix.target }}/release/pre
            target/${{ matrix.target }}/release/pre.exe
            target/${{ matrix.target }}/release/post
            target/${{ matrix.target }}/release/post.exe
  draft-release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: |
          for target in *; do
            [[ $target == *windows* ]] && exe='.exe' || exe=''
            mv "$target/main$exe" "main-$target$exe"
            mv "$target/pre$exe" "pre-$target$exe" || true
            mv "$target/post$exe" "post-$target$exe" || true
            rm -rf "$target"
          done
      - run: gh release create ' ' ./* --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
