name: Draft Release
on: workflow_dispatch
jobs:
  build:
    strategy:
      matrix:
        include:
          - { os: ubuntu-latest, target: x86_64-unknown-linux-gnu }
          - { os: macos-latest, target: x86_64-apple-darwin }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    env:
      target: ${{ matrix.target }}
    steps:
      - uses: actions/checkout@v4
      - run: rustup target add "$target"
      - run: cargo fetch
      - run: cargo build --bin main --locked --release --target "$target"
      # - run: cargo build --bin pre --locked --release --target "$target"
      # - run: cargo build --bin post --locked --release --target "$target"
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target }}
          path: |
            target/${{ matrix.target }}/release/main?(.exe)
            target/${{ matrix.target }}/release/pre?(.exe)
            target/${{ matrix.target }}/release/post?(.exe)
  draft-release:
    needs: build
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
      - run: tree -a
      - run: |
          for target in *; do
            [[ $target == *windows* ]] && s='.exe' || s=''
            mv "$target/main$s" "main-$target$s"
            mv "$target/pre$s" "pre-$target$s" || true
            mv "$target/post$s" "post-$target$s" || true
            rm -rf "$target"
          done
      - run: tree -a
      - run: gh release create ' ' ./* --draft
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
